### PR TITLE
Remove connectivity listener

### PR DESCRIPTION
**Pull request by ashughes**
Fixes NPE during authentication.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @ashughes, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by ashughes** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @ashughes has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by doncung** [comment]
Thanks for the pull request. The connectivity listener is used to refresh the page when the connection is regained. I believe we fixed the crash in the baymax branch which we will be merging on Monday.

**Comment by ashughes** [comment]
I just tested version 4.0.1 and still got this same NPE:

    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x10000010 (has extras) } in com.box.androidsdk.content.auth.OAuthActivity$1@41c06f68
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:737)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4514)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
        at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.NullPointerException
        at com.box.androidsdk.content.auth.OAuthActivity.isAuthErrored(OAuthActivity.java:152)
        at com.box.androidsdk.content.auth.OAuthActivity$1.onReceive(OAuthActivity.java:95)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
        at android.os.Handler.handleCallback(Handler.java:605) 
        at android.os.Handler.dispatchMessage(Handler.java:92) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4514) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
        at dalvik.system.NativeStart.main(Native Method)

**Pull request closed without merging**
